# Generated by Django 2.2 on 2019-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piusairline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerID', models.IntegerField()),
                ('staffID', models.IntegerField()),
                ('salesLocation', models.TextField()),
                ('paymentType', models.TextField()),
                ('flightName', models.TextField()),
                ('destination', models.TextField()),
                ('departureLocation', models.TextField()),
                ('departureDate', models.DateTimeField()),
                ('arrivalDate', models.DateTimeField()),
            ],
        ),
    ]
