# Generated by Django 2.2 on 2019-05-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('piusairline', '0003_airlineusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersdetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Airlineusers',
        ),
    ]
