# Generated by Django 2.2 on 2019-06-07 10:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piusairline', '0007_auto_20190602_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='staffID',
            new_name='ticketID',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='salesLocation',
        ),
        migrations.AddField(
            model_name='sales',
            name='dateSold',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickets',
            name='arrivalDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 11, 18, 49, 552927)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='departureDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 11, 18, 49, 552927)),
        ),
    ]
